# Generated by Django 5.0 on 2025-11-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('apoderado', 'Apoderado'), ('profesor', 'Profesor'), ('inspector', 'Inspector'), ('director', 'Director')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorApp.apoderado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.usuario')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('motivo', models.TextField()),
                ('archivo_pdf', models.FileField(upload_to='certificados/')),
                ('validado', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='gestorApp.alumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_subidos', to='gestorApp.apoderado')),
            ],
            options={
                'verbose_name': 'Certificado Médico',
                'verbose_name_plural': 'Certificados Médicos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.director')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.usuario')),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectores',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.director')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.profesor'),
        ),
        migrations.AddField(
            model_name='director',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.usuario'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorApp.usuario'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Retirado', 'Retirado')], default='Ausente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestorApp.alumno')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_autorizados', to='gestorApp.apoderado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'alumno__usuario__nombre'],
                'indexes': [models.Index(fields=['fecha', 'estado'], name='gestorApp_a_fecha_b6ed82_idx'), models.Index(fields=['alumno', 'fecha'], name='gestorApp_a_alumno__7670f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Atraso', 'Atraso'), ('Inasistencia', 'Inasistencia'), ('Inasistencia Prolongada', 'Inasistencia Prolongada'), ('Certificado Médico', 'Certificado Médico'), ('Certificado Validado', 'Certificado Validado'), ('Certificado Rechazado', 'Certificado Rechazado'), ('Retiro', 'Retiro'), ('General', 'General')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestorApp.alumno')),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_recibidas', to='gestorApp.apoderado')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='gestorApp.inspector')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['-fecha_envio'], name='gestorApp_n_fecha_e_69b46c_idx'), models.Index(fields=['apoderado', '-fecha_envio'], name='gestorApp_n_apodera_46880d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Login', 'Inicio de Sesión'), ('Logout', 'Cierre de Sesión'), ('Registro Usuario', 'Registro de Usuario'), ('Modificación de Asistencia', 'Modificación de Asistencia'), ('Exportación de Reporte', 'Exportación de Reporte'), ('Validación Certificado', 'Validación de Certificado'), ('Rechazo Certificado', 'Rechazo de Certificado'), ('Cambio Contraseña', 'Cambio de Contraseña'), ('Envío Notificación', 'Envío de Notificación'), ('Otro', 'Otra Acción')], help_text='Tipo de acción realizada', max_length=100)),
                ('detalle', models.TextField(help_text='Descripción detallada de la acción')),
                ('tabla_afectada', models.CharField(help_text='Tabla o modelo afectado', max_length=50)),
                ('registro_id', models.IntegerField(blank=True, help_text='ID del registro modificado', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='gestorApp.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='gestorApp_a_fecha_h_09e689_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='gestorApp_a_usuario_de10b4_idx'), models.Index(fields=['tabla_afectada'], name='gestorApp_a_tabla_a_b72e41_idx'), models.Index(fields=['accion'], name='gestorApp_a_accion_d21aa3_idx')],
            },
        ),
    ]
