# Generated by Django 5.0 on 2025-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'fecha')},
        ),
    ]
