# Generated by Django 5.0 on 2025-11-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorApp', '0002_alter_asistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora_marcaje',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se marcó/actualizó la asistencia', null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='marcado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que marcó la asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_marcadas', to='gestorApp.usuario'),
        ),
    ]
